#!/bin/bash
echo Compiling
# --self-contained can be used to embed resources
pandoc main.md -o index.html --template=bootstrap_menu.html
echo Compiled

echo Uploading to Github
git add *
git commit -m "update"
git push
echo Uploaded
